# Generated by Django 6.0.7 on 2026-08-10 06:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryTypeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(max_length=50, unique=True)),
                ('mild_days', models.PositiveIntegerField()),
                ('moderate_days', models.PositiveIntegerField()),
                ('severe_days', models.PositiveIntegerField()),
                ('avoid_exercises_tagged', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('knee', 'Knee'), ('shoulder', 'Shoulder'), ('lower_back', 'Lower Back'), ('ankle', 'Ankle'), ('wrist', 'Wrist'), ('neck', 'Neck'), ('elbow', 'Elbow'), ('hip', 'Hip'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('rest_period_days', models.PositiveIntegerField()),
                ('rest_period_source', models.CharField(choices=[('doctor_provided', 'Doctor Provided'), ('system_calculated', 'System Calculated')], max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('recovery_start_date', models.DateField()),
                ('expected_recovery_date', models.DateField()),
                ('status', models.CharField(choices=[('active_recovery', 'Active Recovery'), ('check_in_pending', 'Check-in Pending'), ('recovered', 'Recovered'), ('recurring', 'Recurring')], default='active_recovery', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='InjuryCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('user_response', models.CharField(blank=True, choices=[('fully_recovered', 'Fully Recovered'), ('partially_recovered', 'Partially Recovered'), ('same', 'Same'), ('worse', 'Worse')], max_length=30, null=True)),
                ('pain_level', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='health.injury')),
            ],
        ),
    ]
