# Generated by Django 6.0.7 on 2026-07-30 06:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gif_url', models.URLField(blank=True, null=True)),
                ('body_parts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('equipments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('target_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('secondary_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('instructions', models.JSONField(default=list)),
                ('is_home_friendly', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
