# Generated by Django 6.0.7 on 2026-08-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 (easiest) to 5 (hardest). AI-assigned + audited.', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_pattern',
            field=models.CharField(blank=True, null=True, verbose_name=[('push_horizontal', 'Horizontal Push'), ('push_vertical', 'Vertical Push'), ('pull_horizontal', 'Horizontal Pull'), ('pull_vertical', 'Vertical Pull'), ('squat', 'Squat'), ('hinge', 'Hip Hinge'), ('lunge', 'Lunge'), ('core', 'Core'), ('isolation_upper', 'Upper Isolation'), ('isolation_lower', 'Lower Isolation'), ('plyometric', 'Plyometric'), ('full_body', 'Full Body')]),
        ),
    ]
