# Generated by Django 6.0.7 on 2026-07-29 09:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_injuries', models.BooleanField(blank=True, null=True)),
                ('injury_details', models.TextField(blank=True, null=True)),
                ('takes_medication_details', models.BooleanField(blank=True, null=True)),
                ('medication_details', models.TextField(blank=True, null=True)),
                ('has_doctor_restriction', models.BooleanField(blank=True, null=True)),
                ('doctor_restriction_detail', models.TextField(blank=True, null=True)),
                ('primary_goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('build_muscle', 'Build muscle'), ('general_fitness', 'General fitness'), ('tone', 'Tone and sculpt')], max_length=20)),
                ('success_vision', models.CharField(choices=[('noticeably_fitter', 'noticeably fitter'), ('clothing_size', 'Down a clothing size'), ('consistent_habit', 'Consistent habit build'), ('muscle_definition', 'Visible muscle definition'), ('other', 'something else')], max_length=20)),
                ('body_type', models.CharField(choices=[('slim', 'Slim'), ('average', 'Average'), ('athletic', 'Athletic'), ('larger_build', 'Larger build')], max_length=20)),
                ('success_vision_other', models.CharField(blank=True, max_length=255, null=True)),
                ('equipment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('no_equipment', 'No equipment'), ('dumbbells', 'Dumbbells'), ('resistance_bands', 'Resistance bands'), ('yoga_mat', 'Yoga mat'), ('bench', 'Bench'), ('kettlebells', 'Kettlebells')], max_length=30), blank=True, default=list)),
                ('time_per_session', models.PositiveSmallIntegerField()),
                ('days_per_week', models.PositiveSmallIntegerField()),
                ('training_style', models.CharField(choices=[('keep_it_simple', 'Keep it simple'), ('open_to_learning', 'Open to learning')], max_length=20)),
                ('workout_focus', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength training'), ('mix', 'A mix of both')], max_length=20)),
                ('sleep_hours', models.CharField(blank=True, choices=[('under_5', 'Under 5h'), ('5_7', '5-7h'), ('7_9', '7-9h'), ('9_plus', '9h+')], max_length=10, null=True)),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('smokes_or_drinks', models.BooleanField(blank=True, null=True)),
                ('eating_habits', models.CharField(choices=[('consistent', 'Pretty consistent'), ('inconsistent', 'Somewhat inconsistent'), ('convenience_food', 'Mostly convenience food')], max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
