# Generated by Django 6.0.7 on 2026-07-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboardingprofile',
            old_name='doctor_restriction_detail',
            new_name='doctor_restriction_details',
        ),
        migrations.RenameField(
            model_name='onboardingprofile',
            old_name='takes_medication_details',
            new_name='takes_medication',
        ),
    ]
