# Generated by Django 6.0.7 on 2026-08-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_rename_doctor_restriction_detail_onboardingprofile_doctor_restriction_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingprofile',
            name='ai_exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
