# Generated by Django 6.0.7 on 2026-08-10 08:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboardingprofile_ai_exclusions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('somatotype', models.CharField(max_length=50)),
                ('estimated_body_fat_range', models.CharField(max_length=20)),
                ('lagging_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('developed_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('posture_notes', models.TextField(blank=True)),
                ('training_focus', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='experience_level',
            field=models.CharField(choices=[('novice', 'Complete Beginner (never trained)'), ('beginner', 'Beginner (< 6 months)'), ('intermediate', 'Intermediate (6 mo - 2 yrs)'), ('advanced', 'Advanced (2+ yr)')], default='novice', max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='PhysiqueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('photo', 'User Photo'), ('internet_image', 'Internet Image'), ('build_template', 'Predefined Build')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('somatotype', models.CharField(blank=True, max_length=50)),
                ('estimated_body_fat_range', models.CharField(blank=True, max_length=20)),
                ('lagging_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('developed_muscles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('posture_notes', models.TextField(blank=True)),
                ('training_focus', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bmr', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('tdee', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('target_calories', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('target_protein_g', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('target_carbs_g', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('target_fats_g', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('shoulder_to_hip_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('shoulder_tilt', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('symmetry_score', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('geometric_somatotype_estimate', models.CharField(blank=True, max_length=50)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='onboarding.buildtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physique_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
