# Generated by Django 6.0.7 on 2026-08-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_buildtemplate_onboardingprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='body_type',
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='cuisine_preference',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingprofile',
            name='dietary_restriction',
            field=models.CharField(blank=True, choices=[('none', 'No restriction'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='none', max_length=20),
        ),
    ]
