# Generated by Django 6.0.7 on 2026-07-31 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('in_progress', 'In progress')], default='in_progress', max_length=20)),
                ('feedback', models.CharField(blank=True, choices=[('too_easy', 'Too easy'), ('just_right', 'Just right'), ('too_hard', 'Too hard')], max_length=20, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout_days', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='plans.workoutday')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_sets', models.PositiveSmallIntegerField(default=0)),
                ('completed_reps', models.CharField(blank=True, max_length=20, null=True)),
                ('weight_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('reported_pain', models.BooleanField(default=False)),
                ('pain_details', models.TextField(blank=True, null=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='plans.workoutexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_log', to='logs.workoutsession')),
            ],
        ),
    ]
