# Generated by Django 6.0.7 on 2026-07-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsession',
            old_name='workout_days',
            new_name='workout_day',
        ),
    ]
