# Generated by Django 6.0.7 on 2026-08-10 06:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("onboarding", "0004_buildtemplate_onboardingprofile_age_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('serving_size', models.CharField(max_length=100)),
                ('serving_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calories', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fats_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sugar_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyFoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='nutrition.fooditem')),
            ],
            options={
                'ordering': ['-date', '-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=50)),
                ('target_calories', models.DecimalField(decimal_places=0, max_digits=6)),
                ('target_protein_g', models.DecimalField(decimal_places=0, max_digits=6)),
                ('target_carbs_g', models.DecimalField(decimal_places=0, max_digits=6)),
                ('target_fats_g', models.DecimalField(decimal_places=0, max_digits=6)),
                ('days_per_week', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_generated_by_ai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('physique_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='onboarding.physiqueprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('pre_workout', 'Pre-Workout'), ('post_workout', 'Post-Workout')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.mealplan')),
            ],
            options={
                'ordering': ['day_number', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('preparation_notes', models.TextField(blank=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='nutrition.fooditem')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='nutrition.meal')),
            ],
            options={
                'unique_together': {('meal', 'food_item')},
            },
        ),
    ]
