# Generated by Django 6.0.7 on 2026-08-11 08:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='contains_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='contains_pork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='cuisine_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
