# Generated by Django 6.0.7 on 2026-08-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_fooditem_contains_alcohol_fooditem_contains_pork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
    ]
