# Generated by Django 6.0.7 on 2026-08-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_fooditem_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='cheat_day_calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='cheat_day_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='has_cheat_day',
            field=models.BooleanField(default=False),
        ),
    ]
