# Generated by Django 6.0.7 on 2026-08-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_mealplan_cheat_day_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='contains_shellfish',
            field=models.BooleanField(default=False),
        ),
    ]
