# Generated by Django 6.0.7 on 2026-07-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='adjustment_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
