# Generated by Django 6.0.7 on 2026-08-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_buildtemplate_onboardingprofile_age_and_more"),
        ('plans', '0002_workoutplan_adjustment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='is_piority',
            field=models.BooleanField(default=False, help_text='Tragets a lagging muscl from physique analysis'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='reason',
            field=models.CharField(blank=True, help_text='Why this exercise was chosen', max_length=255),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='physique_profile',
            field=models.ForeignKey(blank=True, help_text='Snapshot of the physique profile that generated this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts_plans', to='onboarding.physiqueprofile'),
        ),
    ]
