# Generated by Django 6.0.7 on 2026-08-11 06:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_workoutexercise_is_piority_workoutexercise_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutday',
            name='focus_muscles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
    ]
