# Generated by Django 6.0.7 on 2026-08-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_workoutday_focus_muscles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='is_piority',
            new_name='is_priority',
        ),
    ]
